#!/bin/bash
# A2A Setup Wizard - Configura el skill para un nuevo agente
# Uso: ./scripts/setup.sh

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="$SCRIPT_DIR/_config.sh"

echo "🔗 A2A Protocol - Setup Wizard"
echo "==============================="
echo ""
echo "Este wizard te ayudará a configurar A2A para tu agente."
echo ""

# Detect if running interactively
if [ -t 0 ]; then
    INTERACTIVE=true
else
    INTERACTIVE=false
fi

# Agent Name
echo "📛 ¿Cuál es el nombre de tu agente?"
echo "   (ej: Sam, Sage, Sybil)"
if [ "$INTERACTIVE" = true ]; then
    read -p "   > " AGENT_NAME
else
    echo "   [No interactivo - usa variables de entorno A2A_AGENT_NAME]"
    AGENT_NAME="${A2A_AGENT_NAME:-}"
fi

if [ -z "$AGENT_NAME" ]; then
    echo "❌ Nombre requerido"
    exit 1
fi

echo ""

# Agent ID
echo "🆔 ¿Cuál es tu Agent ID (UUID)?"
echo "   Agentes conocidos:"
echo "   - Sam:   62bb0f39-2248-4b14-806d-1c498c654ee7"
echo "   - Sage:  f6198962-313d-4a39-89eb-72755602d468"
echo "   - Sybil: 5fae1839-ab85-412c-acc0-033cbbbbd15b"
echo ""
echo "   Si eres uno de estos, escribe solo el nombre (sam/sage/sybil)"
echo "   Si no, pega tu UUID completo"

if [ "$INTERACTIVE" = true ]; then
    read -p "   > " AGENT_INPUT
else
    AGENT_INPUT="${A2A_AGENT_ID:-}"
fi

# Resolve agent ID
case "${AGENT_INPUT,,}" in
    sam)
        AGENT_ID="62bb0f39-2248-4b14-806d-1c498c654ee7"
        ;;
    sage)
        AGENT_ID="f6198962-313d-4a39-89eb-72755602d468"
        ;;
    sybil)
        AGENT_ID="5fae1839-ab85-412c-acc0-033cbbbbd15b"
        ;;
    *)
        AGENT_ID="$AGENT_INPUT"
        ;;
esac

if [ -z "$AGENT_ID" ]; then
    echo "❌ Agent ID requerido"
    exit 1
fi

# Validate UUID format (basic check)
if [[ ! "$AGENT_ID" =~ ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$ ]]; then
    echo "⚠️  Advertencia: '$AGENT_ID' no parece ser un UUID válido"
    echo "   Continuando de todos modos..."
fi

echo ""

# Telegram (optional)
echo "📱 ¿Quieres configurar notificaciones de Telegram? (opcional)"
echo "   Esto requiere un bot token de @BotFather"

if [ "$INTERACTIVE" = true ]; then
    read -p "   ¿Configurar Telegram? (s/N) > " SETUP_TELEGRAM
else
    SETUP_TELEGRAM="n"
fi

TELEGRAM_BOT_TOKEN=""
TELEGRAM_CHAT_ID="-5165191591"
TELEGRAM_AGENT_TAG=""

if [[ "${SETUP_TELEGRAM,,}" == "s" || "${SETUP_TELEGRAM,,}" == "y" ]]; then
    echo ""
    read -p "   Bot Token (de @BotFather) > " TELEGRAM_BOT_TOKEN
    
    echo "   Chat ID para notificaciones"
    echo "   (default: -5165191591 = grupo BJS alertas)"
    read -p "   > " TG_CHAT_INPUT
    if [ -n "$TG_CHAT_INPUT" ]; then
        TELEGRAM_CHAT_ID="$TG_CHAT_INPUT"
    fi
    
    echo "   Tag de tu bot (ej: @sam_ctxt_bot)"
    read -p "   > " TELEGRAM_AGENT_TAG
fi

echo ""

# Relay URL
RELAY_URL="https://a2a-bjs-internal-skill-production.up.railway.app"
echo "🌐 Relay URL: $RELAY_URL"
echo "   (cambia esto solo si tienes tu propio relay)"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📋 Resumen de configuración:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "   Nombre:    $AGENT_NAME"
echo "   Agent ID:  $AGENT_ID"
echo "   Relay:     $RELAY_URL"
if [ -n "$TELEGRAM_BOT_TOKEN" ]; then
    echo "   Telegram:  ✅ Configurado"
    echo "   Chat ID:   $TELEGRAM_CHAT_ID"
    echo "   Bot Tag:   $TELEGRAM_AGENT_TAG"
else
    echo "   Telegram:  ❌ No configurado"
fi
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

if [ "$INTERACTIVE" = true ]; then
    read -p "¿Guardar configuración? (S/n) > " CONFIRM
    if [[ "${CONFIRM,,}" == "n" ]]; then
        echo "❌ Cancelado"
        exit 0
    fi
fi

# Write config file
cat > "$CONFIG_FILE" << EOF
#!/bin/bash
# A2A Configuration - Generated by setup.sh
# $(date)

# Relay server
export A2A_RELAY_URL="$RELAY_URL"

# Your agent info
export A2A_AGENT_ID="$AGENT_ID"
export A2A_AGENT_NAME="$AGENT_NAME"

# Telegram notifications (optional)
export TELEGRAM_BOT_TOKEN="$TELEGRAM_BOT_TOKEN"
export TELEGRAM_CHAT_ID="$TELEGRAM_CHAT_ID"
export TELEGRAM_AGENT_TAG="$TELEGRAM_AGENT_TAG"

# Data directory (don't change unless you know what you're doing)
export A2A_DATA_DIR="\${A2A_DATA_DIR:-\$HOME/.openclaw/a2a}"
EOF

chmod +x "$CONFIG_FILE"

echo "✅ Configuración guardada en: $CONFIG_FILE"
echo ""

# Create data directory
DATA_DIR="${A2A_DATA_DIR:-$HOME/.openclaw/a2a}"
mkdir -p "$DATA_DIR"
echo "✅ Directorio de datos creado: $DATA_DIR"
echo ""

# Install dependencies
echo "📦 Instalando dependencias..."
cd "$SCRIPT_DIR/../daemon"
if [ -f "package.json" ]; then
    npm install --silent 2>/dev/null || npm install
    echo "✅ Dependencias instaladas"
else
    echo "⚠️  No se encontró package.json en daemon/"
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🎉 ¡Setup completado!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Próximos pasos:"
echo ""
echo "1. Inicia el daemon:"
echo "   $SCRIPT_DIR/daemon-start.sh"
echo ""
echo "2. Verifica que funciona:"
echo "   $SCRIPT_DIR/test.sh"
echo ""
echo "3. Envía tu primer mensaje:"
echo "   $SCRIPT_DIR/daemon-send.sh sam '{\"saludo\":\"Hola desde $AGENT_NAME!\"}'"
echo ""
echo "📚 Documentación: cat $SCRIPT_DIR/../SKILL.md"
echo ""
